name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: xvfb-run -a npm test

    - name: Auto-merge minor/patch updates
      uses: pascalgn/merge-action@v0.15.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        merge_method: squash
      if: contains(github.event.pull_request.title, 'bump') && !contains(github.event.pull_request.title, 'major')
